### ISSUE TITLE
Apostrophe and other [^a-zA-Z] characters

### ISSUE THREAD

**Issue by missinglink** [pelias/suggester-pipeline#2]
The following POI is not suggestable by "Goldsmiths Square" due to the apostrophe.

```javascript
{
    "_index": "pelias",
    "_type": "osmway",
    "_id": "48704534",
    "_version": 1,
    "found": true,
    "_source": {
        "type": "way",
        "name": {
            "default": "Goldsmiths' Square"
        },
        "center_point": {
            "lat": "51.533952",
            "lon": "-0.063600"
        },
        "admin0": "United Kingdom",
        "admin1": "Hackney",
        "admin2": "Haggerston",
        "suggest": {
            "input": ["goldsmiths' square"],
            "payload": {
                "id": "osmway/48704534",
                "geo": "-0.063600,51.533952"
            },
            "output": "Goldsmiths' Square, Haggerston, United Kingdom"
        }
    }
}
```

**Comment by missinglink** [comment]
This seems to be resolved, possibly by `pelias/elasticsearch-plugin`?

http://pelias.mapzen.com/doc?id=osmway:48704534
http://pelias.mapzen.com/suggest?input=Goldsmiths%20Square&lon=-0.063634&lat=51.533948

**Comment by sevko** [comment]
@hkrishna , weigh in?

**Comment by hkrishna** [comment]
Yes - this is resolved. you can search for a [doc](http://pelias.mapzen.com/doc?id=osmway:48704534) with queries [1] and [2]

[1] http://pelias.mapzen.com/suggest?input=Goldsmiths%20Square&lon=-0.063634&lat=51.533948
[2] http://pelias.mapzen.com/suggest?input=Goldsmiths%27%20Square&lon=-0.063634&lat=51.533948
