### ISSUE TITLE
Ampersands in names

### ISSUE THREAD

**Issue by missinglink** [pelias/suggester-pipeline#4]
The following POI should be searchable via `&` or `and`

```
Hale & Hearty Soup -> Hale and Hearty Soup
```

**Comment by missinglink** [comment]
@hkrishna this is an old ticket, did this issue get resolved some time ago by `pelias/elasticsearch-plugin`?

I guess as long as we use that analyser for the suggester fields then this is no longer an issue?

**Comment by missinglink** [comment]
@sevko pending feedback from harish we can probably cover this issue with a regression test and close this ticket.

**Comment by hkrishna** [comment]
@missinglink I don't think this is working as we'd like it to work. Its replacing [&] and [and] tokens - making it impossible to search using `&`, `and`

It needs to be investigated a little further.

**Comment by missinglink** [comment]
this issue has been resolved by the ngrams release
