### ISSUE TITLE
trim tokens

### ISSUE THREAD

**Issue by missinglink** [pelias/suggester-pipeline#5]
Leading and trailing spaces should be removed from tokens, eg:

```
text: "Caltex , Woodville, New Zealand"
```

**Comment by sevko** [comment]
My instinct is that this should be importers' concern, but there's no use in replicating the same string trimming (and possibly more) logic in every one of them. I imagine we should `.trim()` `.name.default`, `.admin0`, `.admin1`, etc. I'm not sure that belongs in `suggester-pipeline`, though.. could put it in the `pelias-model` setters.

**Comment by sevko** [comment]
Looks like we already support adding transform functions to property-setters in `pelias-model` (thanks @hkrishna). I'm thinking of migrating this issue to that repo. @missinglink ?

**Comment by missinglink** [comment]
agree
